import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

const ROOT_DIR = process.cwd();
const PROJECTS_DIR = path.join(ROOT_DIR, 'projects');
const PRIVATE_PROJECTS_DIR = path.join(PROJECTS_DIR, '_private');
const TEMPLATE_DIR = path.join(PROJECTS_DIR, '_template');
const GENERATED_REGISTRY_FILE = path.join(
  ROOT_DIR,
  'src',
  'core',
  'registry',
  'projects-registry.generated.ts'
);
const LOCAL_REGISTRY_FILE = path.join(
  ROOT_DIR,
  'src',
  'core',
  'registry',
  'projects-registry.local.generated.ts'
);

function toPascalCase(str: string): string {
  return str
    .split('-')
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join('');
}

function toCamelCase(str: string): string {
  const pascal = toPascalCase(str);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

export function regenerateAllRegistries(): void {
  // 1. Regenerar registry público/versionável
  const publicEntries = fs.readdirSync(PROJECTS_DIR, { withFileTypes: true });
  const publicSlugs = publicEntries
    .filter(
      (entry) =>
        entry.isDirectory() &&
        !entry.name.startsWith('_') &&
        fs.existsSync(path.join(PROJECTS_DIR, entry.name, 'project.config.ts'))
    )
    .map((entry) => entry.name)
    .sort();

  const publicImports = publicSlugs
    .map((slug) => {
      const varName = toCamelCase(slug);
      return `import { project as ${varName} } from '../../../projects/${slug}';`;
    })
    .join('\n');

  const publicExportsArray = publicSlugs
    .map((slug) => `  ${toCamelCase(slug)},`)
    .join('\n');

  const publicContent = `// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Generated by scripts/new-project.ts
import type { RegisteredProject } from './project-contract';

${publicImports}

export const generatedProjects: RegisteredProject[] = [
${publicExportsArray}
];
`;

  fs.writeFileSync(GENERATED_REGISTRY_FILE, publicContent, 'utf-8');
  console.log('✅ Registry versionado atualizado em projects-registry.generated.ts');

  // 2. Regenerar registry local/privado (gitignored)
  let privateSlugs: string[] = [];
  if (fs.existsSync(PRIVATE_PROJECTS_DIR)) {
    const privateEntries = fs.readdirSync(PRIVATE_PROJECTS_DIR, { withFileTypes: true });
    privateSlugs = privateEntries
      .filter(
        (entry) =>
          entry.isDirectory() &&
          !entry.name.startsWith('_') &&
          fs.existsSync(path.join(PRIVATE_PROJECTS_DIR, entry.name, 'project.config.ts'))
      )
      .map((entry) => entry.name)
      .sort();
  }

  const privateImports = privateSlugs
    .map((slug) => {
      const varName = toCamelCase(slug);
      return `import { project as ${varName} } from '../../../projects/_private/${slug}';`;
    })
    .join('\n');

  const privateExportsArray = privateSlugs
    .map((slug) => `  ${toCamelCase(slug)},`)
    .join('\n');

  const privateContent = `// AUTO-GENERATED FILE. LOCAL / PRIVATE PROJECTS REGISTRY.
// This file is gitignored and will not be tracked in Git.
import type { RegisteredProject } from './project-contract';

${privateImports ? privateImports + '\n\n' : ''}export const localProjects: RegisteredProject[] = [
${privateExportsArray}
];
`;

  fs.writeFileSync(LOCAL_REGISTRY_FILE, privateContent, 'utf-8');
  console.log('🔒 Registry local atualizado em projects-registry.local.generated.ts');
}

function copyRecursiveSync(src: string, dest: string): void {
  const exists = fs.existsSync(src);
  const stats = exists && fs.statSync(src);
  const isDirectory = exists && stats && stats.isDirectory();

  if (isDirectory) {
    if (!fs.existsSync(dest)) {
      fs.mkdirSync(dest, { recursive: true });
    }
    fs.readdirSync(src).forEach((childItemName) => {
      copyRecursiveSync(
        path.join(src, childItemName),
        path.join(dest, childItemName)
      );
    });
  } else {
    fs.copyFileSync(src, dest);
  }
}

function replaceInFiles(dir: string, fromRegex: RegExp, toStr: string): void {
  const files = fs.readdirSync(dir, { withFileTypes: true });
  for (const file of files) {
    const fullPath = path.join(dir, file.name);
    if (file.isDirectory()) {
      replaceInFiles(fullPath, fromRegex, toStr);
    } else if (file.isFile() && /\.(ts|tsx|md|json)$/.test(file.name)) {
      let content = fs.readFileSync(fullPath, 'utf-8');
      content = content.replace(fromRegex, toStr);
      fs.writeFileSync(fullPath, content, 'utf-8');
    }
  }
}

function createStandardAssetFolders(publicAssetsDir: string, slug: string, isPrivate: boolean): void {
  const subdirs = [
    {
      name: 'assets',
      description:
        '# Assets Versionáveis\nArquivos leves e essenciais (logos, SVGs, áudios pequenos) que podem ser commitados no Git quando o projeto for público.\n',
    },
    {
      name: 'raw',
      description:
        '# Raw Media (Material Bruto)\nVídeos pesados, gravações de câmera, arquivos brutos. NUNCA é versionado pelo Git.\n',
    },
    {
      name: 'generated',
      description:
        '# Generated Assets\nImagens, áudios e mídias geradas por IA ou ferramentas locais. Protegido pelo .gitignore.\n',
    },
    {
      name: 'exports',
      description:
        '# Project Exports\nRenderizações intermediárias, testes e exports específicos deste projeto. Protegido pelo .gitignore.\n',
    },
  ];

  for (const { name, description } of subdirs) {
    const dirPath = path.join(publicAssetsDir, name);
    fs.mkdirSync(dirPath, { recursive: true });
    // Adiciona .gitkeep explicativo se for assets, ou nos demais para documentar localmente
    fs.writeFileSync(path.join(dirPath, '.gitkeep'), description, 'utf-8');
  }

  console.log(`📁 Estrutura de assets criada em: public/${isPrivate ? 'projects/_private/' : 'projects/'}${slug}/ (assets, raw, generated, exports)`);
}

async function main(): Promise<void> {
  const rawArgs = process.argv.slice(2);

  if (rawArgs.includes('--regenerate-only')) {
    regenerateAllRegistries();
    return;
  }

  const isPrivate = rawArgs.includes('--private');
  const nonFlagArgs = rawArgs.filter((arg) => !arg.startsWith('--'));
  const slug = nonFlagArgs[0];

  if (!slug) {
    console.error('❌ Erro: Informe o slug do projeto.');
    console.error('Uso normal:   npm run new-project meu-video');
    console.error('Uso privado:  npm run new-project meu-video --private');
    process.exit(1);
  }

  // 1. Validar slug (apenas letras minúsculas, números e hífens)
  const slugRegex = /^[a-z0-9]+(-[a-z0-9]+)*$/;
  if (!slugRegex.test(slug)) {
    console.error(`❌ Erro: Slug inválido "${slug}".`);
    console.error('O slug deve conter apenas letras minúsculas, números e hífens (kebab-case).');
    process.exit(1);
  }

  // 2. Determinar caminhos de destino
  const targetProjectDir = isPrivate
    ? path.join(PRIVATE_PROJECTS_DIR, slug)
    : path.join(PROJECTS_DIR, slug);

  // Verificar se o projeto já existe (seja em público ou privado)
  const publicCheckPath = path.join(PROJECTS_DIR, slug);
  const privateCheckPath = path.join(PRIVATE_PROJECTS_DIR, slug);

  if (fs.existsSync(publicCheckPath)) {
    console.error(`❌ Erro: O projeto "${slug}" já existe na pasta pública: projects/${slug}`);
    process.exit(1);
  }
  if (fs.existsSync(privateCheckPath)) {
    console.error(`❌ Erro: O projeto "${slug}" já existe na pasta privada: projects/_private/${slug}`);
    process.exit(1);
  }

  console.log(`🚀 Criando novo projeto ${isPrivate ? '🔒 PRIVADO' : '🌐 PÚBLICO'} "${slug}"...`);

  // 3. Copiar template
  copyRecursiveSync(TEMPLATE_DIR, targetProjectDir);

  // 4. Configurar substituições
  const titleName = toPascalCase(slug).replace(/([A-Z])/g, ' $1').trim();
  const today = new Date().toISOString().split('T')[0];
  const assetsRelativePath = isPrivate
    ? `projects/_private/${slug}`
    : `projects/${slug}`;

  // Substituições nos arquivos do projeto
  replaceInFiles(targetProjectDir, /_template/g, slug);
  replaceInFiles(targetProjectDir, /Template Starter/g, titleName);
  replaceInFiles(targetProjectDir, /'draft'/g, "'active'");
  replaceInFiles(targetProjectDir, /enabled: false/g, 'enabled: true');
  replaceInFiles(targetProjectDir, /'2026-09-16'/g, `'${today}'`);
  replaceInFiles(targetProjectDir, /assetsPath: 'projects\/_template'/g, `assetsPath: '${assetsRelativePath}'`);

  // 5. Criar pasta pública de assets com estrutura padrão (assets, raw, generated, exports)
  const publicAssetsDir = isPrivate
    ? path.join(ROOT_DIR, 'public', 'projects', '_private', slug)
    : path.join(ROOT_DIR, 'public', 'projects', slug);

  createStandardAssetFolders(publicAssetsDir, slug, isPrivate);

  // 6. Regenerar registries (público e privado)
  regenerateAllRegistries();

  // 7. Executar smoke typecheck
  console.log('🔍 Executando verificação de tipos (tsc --noEmit)...');
  try {
    execSync('npx tsc --noEmit', { stdio: 'inherit' });
    console.log(`\n✨ Projeto "${slug}" criado e registrado com sucesso!`);
    console.log(`📁 Localização do código: ${isPrivate ? 'projects/_private/' : 'projects/'}${slug}`);
    console.log(`🔒 Status no Git: ${isPrivate ? 'IGNORADO (Privado/Local)' : 'VERSIONÁVEL (Público)'}`);
    console.log(`🎨 Para editar: abra ${isPrivate ? 'projects/_private/' : 'projects/'}${slug}/index.tsx`);
    console.log(`👀 Para visualizar no Remotion Studio: npm run dev\n`);
  } catch {
    console.error('❌ Erro na validação de tipos do novo projeto.');
    process.exit(1);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
