// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Generated by scripts/new-project.ts
import type { RegisteredProject } from './project-contract';

import { project as project_demo_showcase } from '../../../projects/demo-showcase';
import { project as project_motion_reference } from '../../../projects/motion-reference';

export const generatedProjects: RegisteredProject[] = [
  project_demo_showcase,
  project_motion_reference,
];
