// AUTO-GENERATED FILE. DO NOT EDIT DIRECTLY.
// Generated by scripts/new-project.ts
import type { RegisteredProject } from './project-contract';

import { project as demoShowcase } from '../../../projects/demo-showcase';

export const generatedProjects: RegisteredProject[] = [
  demoShowcase,
];
